name: tf2
channels:
  - defaults
dependencies:
- python=3.9.7
- pip=21.2.4
- cudatoolkit=11.3.1
- cudnn=8.2.1
- pip:
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow
  - tensorflow-gpu
  - torch
