name: tf2
channels:
  - defaults
dependencies:
- python=3.9.7
- pip=21.2.4
- cudnn=8.2.1
- cudatoolkit=11.3.1
- setuptools=58.0.4
- pip:
  - cupy-cuda113==10.4.0
  - matplotlib==3.5.0
  - numpy==1.19.5
  - pandas==1.3.5
  - scikit-learn==1.0.1
  - scipy==1.7.2
  - seaborn==0.11.2
  - tensorflow==2.6.2
  - tensorflow-gpu==2.6.0
  - torch==1.11.0
