name: tf2
channels:
  - defaults
dependencies:  
- pip=21.2.4
- cudatoolkit=11.3.1
- cudnn=8.2.1
- pip:
  - cupy==10.4.0
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow
  - tensorflow-gpu
  - torch
