name: tf
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - abseil-cpp=20210324.2
  - absl-py=0.13.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2022.3.29
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=3.4.8
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - frozenlist=1.2.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.3
  - importlib-metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - keras-preprocessing=1.1.2
  - libcurl=7.78.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libssh2=1.9.0
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.1.0
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - notebook=6.4.8
  - oauthlib=3.1.1
  - openssl=1.1.1n
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - protobuf=3.14.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - pyzmq=22.3.0
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - snappy=1.1.8
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.36.0
  - stack_data=0.2.0
  - tensorboard-plugin-wit=1.6.0
  - termcolor=1.1.0
  - terminado=0.13.1
  - testpath=0.5.0
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.0.2
  - wheel=0.35.1
  - wrapt=1.13.3
  - yarl=1.6.3
  - zipp=3.6.0
  - zlib=1.2.11
  - pip:
    - clang==5.0
    - cycler==0.11.0
    - dill==0.3.4
    - flatbuffers==1.12
    - fonttools==4.28.3
    - googleapis-common-protos==1.56.0
    - h5py==3.1.0
    - joblib==1.1.0
    - jupyter-http-over-ws==0.0.8
    - keras==2.6.0
    - kiwisolver==1.3.2
    - llvmlite==0.37.0
    - matplotlib==3.5.0
    - numba==0.54.1
    - numpy==1.19.5
    - opencv-python==4.5.4.60
    - pandas==1.3.5
    - pillow==8.4.0
    - promise==2.3
    - pyparsing==3.0.6
    - pytz==2021.3
    - pywinpty==1.1.6
    - pyyaml==6.0
    - scikit-learn==1.0.1
    - seaborn==0.11.2
    - setuptools-scm==6.3.2
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorflow==2.6.2
    - tensorflow-datasets==4.5.2
    - tensorflow-estimator==2.6.0
    - tensorflow-gpu==2.6.0
    - tensorflow-metadata==1.7.0
    - threadpoolctl==3.0.0
    - tomli==1.2.2
    - torch==1.11.0
    - tqdm==4.64.0
    - typing-extensions==3.7.4.3
