name: tf2
channels:
  - defaults
dependencies:  
- pip
- cudatoolkit
- cudnn
- pip:
  - cupy
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow
  - tensorflow-gpu
  - torch
